SCREEN_WIDTH = 1980
SCREEN_HEIGHT = 1020

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
PLAYER_LIVES = 3
RESPAWN_TIME = 3.0  # seconds of invincibility after respawn
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
SHOT_RADIUS = 2
PLAYER_SHOOT_COOLDOWN = 0.3  # seconds